apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: magento
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  serviceName: redis-service
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.4.1
        ports:
        - containerPort: 6379
          name: main
