apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: magento-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: azurefile-sc
