apiVersion: v1
kind: Service
metadata:
  name: magento-service
  namespace: magento
spec:
  selector:
    app: magento-server
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
