apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: magento-secret-provider
  namespace: magento
spec:
  provider: azure
  secretObjects:
  - secretName: magento-secret
    type: kubernetes.io/tls
    data:
    - objectName: __CERTIFICATE_NAME__
      key: tls.crt
    - objectName: __CERTIFICATE_NAME__
      key: tls.key
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" 
    userAssignedIdentityID: __USER_ASSIGNED_IDENTITY_ID__
    keyvaultName: __KEYVAULT_NAME__
    objects: |
      array:
        - |
          objectName: __CERTIFICATE_NAME__
          objectType: secret
          objectFormat: "pem"
    tenantId: __TENANT_ID__
