{
 "title": "Azure MySQL Flexible Server Monitor",
 "description": "Azure Database Server for MySQL Flexible Server, metrics via Azure Monitor and MySQL Performance Schema",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resource",
    "label": "Resource",
    "query": {}
   },
   {
    "name": "ds",
    "label": "Data Source",
    "query": "grafana-azure-monitor-datasource"
   },
   {
    "name": "subscription",
    "label": "Subscription",
    "query": {}
   },
   {
    "name": "resource_group",
    "label": "Resource Group",
    "query": {}
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "CPU/memory/IO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "cpu_percent",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "cpu_credits_remaining",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "cpu_credits_consumed",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Memory percent",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "memory_percent",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "available_memory_bytes",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "microsoft.dbformysql/flexibleservers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "io_consumption_percent",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_io_count",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Connectiions",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "active_connections",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "total_connections",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Threads_running",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "failed connections",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "aborted_connections",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "HA Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "HA Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HA_IO_status",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HA_SQL_status",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "HA_replication_lag",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "storage used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "storage_used",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_percent",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "storage_limit",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "binlog_storage_used",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "ibdata1_storage_used",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "backup storage used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "backup_storage_used",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resourceGroup": "$resource_group",
      "resourceName": "$resource",
      "timeGrain": "auto",
      "top": ""
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "network in",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "dimensionFilters": [],
      "metricDefinition": "Microsoft.DBforMySQL/flexibleServers",
      "metricName": "network_bytes_ingress",
      "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
      "resources": [
       { "resourceGroup": "$resource_group", "resourceName": "$resource" }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "network_bytes_egress",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "Workload", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Queries",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Slow_queries",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "microsoft.dbformysql/flexibleservers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "DML",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_select",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_update",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_insert",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_delete",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "DDL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_create_db",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_drop_db",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_alter_table",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_alter_table",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_create_table",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Com_drop_table",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  { "title": "InnoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Buffer Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Innodb_buffer_pool_pages_data",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Innodb_buffer_pool_pages_dirty",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Innodb_buffer_pool_pages_free",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Buffer Pool read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Innodb_buffer_pool_reads",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    {
     "azureMonitor": {
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Innodb_buffer_pool_read_requests",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    },
    { "expression": "100*(1 - $A/$B)", "type": "math" }
   ]
  },
  {
   "title": "Hot data in Buffer pool",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  IF (\r\n    LOCATE ('.', ibp.table_name) = 0,\r\n    'InnoDB System',\r\n    REPLACE (SUBSTRING_INDEX (ibp.table_name, '.', 1), '`', '')\r\n  ) AS object_schema,\r\n  sys.format_bytes(\r\n    SUM(IF(ibp.compressed_size = 0, 16384, compressed_size))\r\n  ) AS allocated,\r\n  sys.format_bytes(SUM(ibp.data_size)) AS data,\r\n  COUNT(ibp.page_number) AS pages,\r\n  COUNT(IF(ibp.is_hashed = 'YES', 1, NULL)) AS pages_hashed,\r\n  COUNT(IF(ibp.is_old = 'YES', 1, NULL)) AS pages_old,\r\n  ROUND(\r\n    SUM(ibp.number_records) / COUNT(DISTINCT ibp.index_name)\r\n  ) AS rows_cached\r\nFROM\r\n  information_schema.innodb_buffer_page ibp\r\nWHERE\r\n  table_name IS NOT NULL\r\nGROUP BY\r\n  object_schema\r\nORDER BY\r\n  SUM(IF(ibp.compressed_size = 0, 16384, compressed_size)) DESC;"
    }
   ]
  },
  { "title": "ps_memory_summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Top Event Memory Usage (MB)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "rawSql": "select event_name, SUM_NUMBER_OF_BYTES_ALLOC/1024/1024 AS SUM_NUMBER_OF_BYTES_ALLOC_MB from performance_schema.memory_summary_global_by_event_name order by SUM_NUMBER_OF_BYTES_ALLOC desc LIMIT 15;"
    }
   ]
  },
  {
   "title": "Host Memory Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "rawSql": "select HOST, EVENT_NAME, SUM_NUMBER_OF_BYTES_ALLOC, concat(SUM_NUMBER_OF_BYTES_ALLOC/1024/1024,'MB') AS SUM_NUMBER_OF_BYTES_ALLOC_MB from performance_schema.memory_summary_by_host_by_event_name order by SUM_NUMBER_OF_BYTES_ALLOC desc limit 10"
    }
   ]
  },
  {
   "title": "Memory allocated to the Event per user",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "rawSql": "SELECT user, host, event_name, current_number_of_bytes_used as current_bytes, high_number_of_bytes_used as high_bytes FROM performance_schema.memory_summary_by_account_by_event_name WHERE current_number_of_bytes_used > 0 ;"
    }
   ]
  },
  {
   "title": "Memory allocated to the Event",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "rawSql": "SELECT event_name, current_number_of_bytes_used as current_bytes, high_number_of_bytes_used as high_bytes FROM performance_schema.memory_summary_global_by_event_name WHERE current_number_of_bytes_used > 0;"
    }
   ]
  },
  { "title": "QueryStore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Top 15 long running (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "targets": [
    {
     "rawSql": "SELECT DIGEST_TEXT,AVG_TIMER_WAIT/1000000000000 AS AVG_TIMER_WAIT_SEC FROM events_statements_summary_by_digest ORDER BY AVG_TIMER_WAIT_SEC DESC LIMIT 15"
    }
   ]
  },
  {
   "title": "TOP 15 most rows examed",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "rawSql": "SELECT DIGEST_TEXT,SUM_ROWS_EXAMINED FROM performance_schema.events_statements_summary_by_digest ORDER BY SUM_ROWS_EXAMINED DESC LIMIT 15;"
    }
   ]
  },
  {
   "title": "Statements with full table scan",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sys.format_Statement(DIGEST_TEXT) AS query,\r\n  SCHEMA_NAME AS db,\r\n  COUNT_STAR AS EXEC_COUNT,\r\n  sys.format_time(SUM_TIMER_WAIT) AS total_latency,\r\n  SUM_NO_INDEX_USED AS NO_index_used_count,\r\n  SUM_NO_GOOD_INDEX_USED AS no_good_index_used_count,\r\n  ROUND (\r\n    ifnull(SUM_NO_INDEX_USED / NULLIF (COUNT_STAR, 0), 0) * 100\r\n  ) AS NO_index_used_pct,\r\n  SUM_ROWS_SENT AS rows_sent,\r\n  SUM_ROWS_EXAMINED AS rows_examined,\r\n  ROUND (SUM_ROWS_SENT / COUNT_STAR) AS rows_sent_avg,\r\n  ROUND (SUM_ROWS_EXAMINED / COUNT_STAR) AS rows_examined_avg,\r\n  FIRST_SEEN AS first_seen,\r\n  LAST_SEEN AS last_seen,\r\n  DIGEST AS digest\r\nFROM\r\n  performance_schema.events_statements_summary_by_digest\r\nWHERE\r\n  (\r\n    SUM_NO_INDEX_USED > 0\r\n    OR SUM_NO_GOOD_INDEX_USED > 0\r\n  )\r\n  AND DIGEST_TEXT NOT LIKE 'SHOW%'\r\nORDER BY\r\n  no_index_used_pct DESC,\r\n  total_latency DESC;"
    }
   ]
  },
  {
   "title": "Statements with file sort",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 146 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  sys.format_statement (DIGEST_TEXT) AS query,\r\n  SCHEMA_NAME db,\r\n  COUNT_STAR AS EXEC_COUNT,\r\n  sys.format_TIME(SUM_TIMER_WAIT) AS total_Latency,\r\n  SUM_SORt_MERGE_PASSES AS sort_merge_passes,\r\n  ROUND (\r\n    IFNULL(SUM_SORT_MERGE_PASSES / NULLIF(COUNT_STAR, 0), 0)\r\n  ) AS avg_sort_merges,\r\n  SUM_SORT_SCAN AS sorts_using_scans,\r\n  SUM_SORT_RANGE AS sort_using_range,\r\n  SUM_SORT_ROWS AS rows_sorted,\r\n  ROUND (IFNULL(SUM_SORT_ROWS / NULLIF(COUNT_STAR, 0), 0)) AS avg_rows_sorted,\r\n  FIRST_SEEN AS first_seen,\r\n  LAST_SEEN AS last_seen,\r\n  DIGEST AS digest\r\nFROM\r\n  performance_schema.events_statements_summary_by_digest\r\nWHERE\r\n  SUM_SORT_ROWS > 0\r\nORDER BY\r\n  SUM_TIMER_WAIT DESC;"
    }
   ]
  },
  {
   "title": "Most executed queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 156 },
   "targets": [
    {
     "rawSql": "SELECT DIGEST_TEXT,COUNT_STAR,FIRST_SEEN,LAST_SEEN FROM events_statements_summary_by_digest ORDER BY COUNT_STAR DESC;\r\n"
    }
   ]
  },
  {
   "title": "Unused indexes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 156 },
   "targets": [
    {
     "rawSql": "SELECT object_schema,\r\n\tobject_name,\r\n    index_name\r\nFROM performance_schema.table_io_waits_summary_by_index_usage\r\nWHERE index_name IS NOT NULL\r\n\tAND count_star = 0\r\n    AND object_schema != 'mysql'\r\n    AND index_name != 'PRIMARY'\r\nORDER BY object_schema, object_name;\r\n"
    }
   ]
  },
  {
   "title": "Temp table usage",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT\r\n  sys.format_statement (DIGEST_TEXT) AS query,\r\n  SCHEMA_NAME AS db,\r\n  COUNT_STAR AS exec_count,\r\n  sys.format_time(SUM_TIMER_WAIT) AS total_latency,\r\n  SUM_CREATED_TMP_TABLES AS memory_tmp_tables,\r\n  SUM_CREATED_TMP_DISK_TABLES AS disk_tmp_tables,\r\n  ROUND (\r\n    IFNULL(SUM_CREATED_TMP_TABLES / NULLIF (COUNT_STAR, 0), 0)\r\n  ) AS avg_tmp_tables_per_query,\r\n  ROUND (\r\n    IFNULL (\r\n      SUM_CREATED_TMP_DISK_TABLES / NULLIF(SUM_CREATED_TMP_TABLES, 0),\r\n      0\r\n    ) * 100\r\n  ) AS tmp_tables_to_disk_pct,\r\n  FIRST_SEEN AS first_seen,\r\n  LAST_SEEN AS last_seen,\r\n  DIGEST AS digest\r\nFROM\r\n  performance_schema.events_statements_summary_bY_digest\r\nWHERE\r\n  SUM_CREATED_TMP_TABLES > 0\r\nORDER BY\r\n  SUM_CREATED_TMP_DISK_TABLES DESC,\r\n  SUM_CREATED_TMP_TABLES DESC;\r\n"
    }
   ]
  },
  {
   "title": "Tables without PK",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 176 },
   "targets": [
    {
     "rawSql": "select tab.table_schema as database_name, tab.table_name\r\nfrom information_schema.tables tab\r\nleft join information_schema.table_constraints tco\r\n          on tab.table_schema = tco.table_schema\r\n          and tab.table_name = tco.table_name\r\n          and tco.constraint_type = 'PRIMARY KEY'\r\nwhere tco.constraint_type is null\r\n      and tab.table_schema not in('mysql', 'information_schema', 'performance_schema', 'sys')\r\n      and tab.table_type = 'BASE TABLE'\r\norder by tab.table_schema, tab.table_name;\r\n"
    }
   ]
  },
  { "title": "ps_wait_summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 184 } },
  {
   "title": "TOP 15 Wait events",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT EVENT_NAME,COUNT_STAR,SUM_TIMER_WAIT/100000000000 AS SUM_TIMER_WAIT_SEC,AVG_TIMER_WAIT/100000000000 AS AVG_TIMER_WAIT_SEC FROM performance_schema.events_waits_summary_global_by_event_name WHERE event_name != 'idle' ORDER BY SUM_TIMER_WAIT_SEC DESC limit 15;\r\n"
    }
   ]
  },
  {
   "title": "Lock wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Maximum",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [],
      "metricName": "Innodb_row_lock_waits",
      "metricNamespace": "microsoft.dbformysql/flexibleservers",
      "resources": [
       {
        "metricNamespace": "Microsoft.DBforMySQL/flexibleServers",
        "resourceGroup": "$resource_group",
        "resourceName": "$resource",
        "subscription": "$subscription"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "$subscription"
    }
   ]
  },
  {
   "title": "Current Wait",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
   "targets": [
    {
     "rawSql": "select sum(TIMER_WAIT)/1000000000000 as TIMER_WAIT_SEC, \r\n\tsys.format_bytes(SUM(NUMBER_OF_BYTES)) as NUMBER_OF_BYTES, \r\n\tEVENT_NAME,\r\n\tOPERATION \r\nfrom performance_schema.events_waits_current \r\nwhere EVENT_NAME != 'idle' \r\ngroup by EVENT_NAME,OPERATION\r\norder by TIMER_WAIT_SEC desc;"
    }
   ]
  },
  {
   "title": "Who hold MDL",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 202 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  g.object_schema AS object_schema,\r\n  g.object_name AS object_name,\r\n  pt.thread_id AS waiting_thread_id,\r\n  pt.processlist_id AS waiting_pid,\r\n  sys.ps_thread_account(p.owner_thread_id) AS waiting_account,\r\n  p.lock_type AS waiting_lock_type,\r\n  p.lock_duration AS waiting_lock_duration,\r\n  sys.format_statement(pt.processlist_info) AS waiting_query,\r\n  pt.processlist_time AS waiting_query_secs,\r\n  ps.rows_affected AS waiting_query_rows_affected,\r\n  ps.rows_examined AS waiting_query_rows_examined,\r\n  gt.thread_id AS blocking_thread_id,\r\n  gt.processlist_id AS blocking_pid,\r\n  sys.ps_thread_account(g.owner_thread_id) AS blocking_account,\r\n  g.lock_type AS blocking_lock_type,\r\n  g.lock_duration AS blocking_lock_duration,\r\n  CONCAT ('KILL QUERY ', gt.processlist_id) AS sql_kill_blocking_query,\r\n  CONCAT ('KILL ', gt.processlist_id) AS sql_kill_blocking_connection\r\nFROM\r\n  performance_schema.metadata_locks g\r\n  INNER JOIN performance_schema.metadata_locks p ON g.object_type = p.object_type\r\n  AND g.object_schema = p.object_schema\r\n  AND g.object_name = p.object_name\r\n  AND g.lock_status = 'GRANTED'\r\n  AND p.lock_status = 'PENDING'\r\n  INNER JOIN performance_schema.threads gt ON g.owner_thread_id = gt.thread_id\r\n  INNER JOIN performance_schema.threads pt ON p.owner_thread_id = pt.thread_id\r\n  LEFT JOIN performance_schema.events_statements_current gs ON g.owner_thread_id = gs.thread_id\r\n  LEFT JOIN performance_schema.events_statements_current ps ON p.owner_thread_id = ps.thread_id\r\nWHERE\r\n  g.object_type = 'TABLE';\r\n"
    }
   ]
  }
 ]
}