apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
