DROP USER IF EXISTS 'MySQLUSERNAME';
FLUSH PRIVILEGES;
CREATE USER 'MySQLUSERNAME'@'%' IDENTIFIED BY 'MySQLUSERLOGINPASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'MySQLUSERNAME'@'%' WITH GRANT OPTION;
DROP USER IF EXISTS 'MONITORINGUSERNAME';
FLUSH PRIVILEGES;
CREATE USER 'MONITORINGUSERNAME'@'%' IDENTIFIED BY 'MONITORINGLOGINPASSWORD';
GRANT SELECT ON *.* TO 'MONITORINGUSERNAME'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;